USE ROLE ACCOUNTADMIN;

SET MY_USER = CURRENT_USER();
CREATE OR REPLACE ROLE TOM_ROLE;
GRANT ROLE TOM_ROLE TO ROLE SYSADMIN;
GRANT ROLE TOM_ROLE TO USER IDENTIFIER($MY_USER);

CREATE OR REPLACE DATABASE TOM_DB;
GRANT OWNERSHIP ON DATABASE TOM_DB TO ROLE TOM_ROLE;

CREATE OR REPLACE WAREHOUSE TOM_WH WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
GRANT OWNERSHIP ON WAREHOUSE TOM_WH TO ROLE TOM_ROLE;


SHOW STAGES;
SHOW ROLES;

GRANT USAGE ON WAREHOUSE TOM_WH TO ROLE TOM_ROL;
GRANT USAGE ON DATABASE TOM_DB TO ROLE TOM_ROL;


CREATE OR REPLACE SCHEMA RAW_TOM;
CREATE OR REPLACE SCHEMA HARMONIZED_TOM;
CREATE OR REPLACE SCHEMA ANALYTICS;
SHOW SCHEMAS;

CREATE OR REPLACE STORAGE INTEGRATION Snowflake_role
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::676206927597:role/Snowflake-role'
ENABLED = TRUE
STORAGE_ALLOWED_LOCATIONS = ('s3://s3-airflow-bucket-1/');

desc integration Snowflake_role;

CREATE OR REPLACE STAGE my_s3_stage
URL = 's3://s3-airflow-bucket-1/tom_db'
STORAGE_INTEGRATION = Snowflake_role;

SHOW SCHEMAS IN DATABASE TOM_DB;

SHOW STAGES;
SHOW GRANTS ON SCHEMA TOM_DB.RAW_TOM;

GRANT USAGE ON SCHEMA TOM_DB.RAW_TOM TO ROLE TOM_ROLE;
GRANT OWNERSHIP ON SCHEMA TOM_DB.RAW_TOM TO ROLE TOM_ROLE;

REVOKE ALL ON SCHEMA TOM_DB.RAW_TOM FROM ROLE TOM_ROLE;

GRANT OWNERSHIP ON SCHEMA TOM_DB.RAW_TOM TO ROLE TOM_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA TOM_DB.ANALYTICS TO ROLE TOM_ROLE REVOKE CURRENT GRANTS;


LIST @my_s3_stage/tom_db;


USE SCHEMA RAW_TOM;


SHOW TABLES IN SCHEMA RAW_TOM;

CREATE OR REPLACE TABLE RAW_TOM_STAGING (
  Rank VARCHAR(10),
  City VARCHAR(100),
  Country VARCHAR(100),
  Avg_Time_Per_6_Miles VARCHAR(50),
  Change_in_Congestion VARCHAR(10),
  Congestion_Level VARCHAR(10),
  Yearly_Delay_Hours VARCHAR(50)
);

SELECT * FROM RAW_TOM.RAW_TOM_STAGING LIMIT 10;

select * from raw_tom_staging;


LIST @my_s3_stage/tom_db;
SHOW TABLES IN SCHEMA RAW_TOM;

GRANT USAGE ON SCHEMA tom_db.raw_tom TO ROLE TOM_ROLE;  -- Grant usage on the schema
GRANT SELECT ON TABLE tom_db.harmonized_tom.harmonized_tom TO ROLE TOM_ROLE;  -- Grant SELECT on the table

GRANT USAGE ON SCHEMA tom_db.raw_tom TO ROLE TOM_ROLE;
GRANT SELECT ON TABLE tom_db.raw_tom.RAW_TOM_STAGING TO ROLE TOM_ROLE;



SHOW TABLES IN SCHEMA HARMONIZED_TOM;

GRANT SELECT ON TABLE "HARMONIZED_TOM"."HARMONIZED_TOM" TO ROLE tom_role;


SHOW GRANTS ON TABLE "HARMONIZED_TOM"."HARMONIZED_TOM";

GRANT USAGE ON SCHEMA "HARMONIZED_TOM" TO ROLE tom_role;
GRANT ALL PRIVILEGES ON TABLE "HARMONIZED_TOM" TO ROLE TOM_ROLE;

TRANSFER OWNERSHIP OF SCHEMA"HARMONIZED_TOM" TO ROLE TOM_ROLE;

ALTER SCHEMA "HARMONIZED_TOM" TRANSFER OWNERSHIP TO ROLE tom_role;

GRANT OWNERSHIP ON SCHEMA "HARMONIZED_TOM" TO ROLE tom_role REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON TABLE TOM_DB.HARMONIZED_TOM.HARMONIZED_TOM TO ROLE TOM_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON TABLE TOM_DB.RAW_TOM.RAW_TOM_STAGING TO ROLE tom_role REVOKE CURRENT GRANTS;

SHOW TABLES LIKE RAW_TOM_STAGING;

USE DATABASE TOM_DB;
USE SCHEMA HARMONIZED_TOM;
SHOW TABLES LIKE 'HARMONIZED_TOM';
SELECT CURRENT_ROLE();

SHOW GRANTS ON SCHEMA TOM_DB.RAW_TOM;
SHOW GRANTS ON TABLE TOM_DB.RAW_TOM.RAW_TOM_STAGING;

USE ROLE TOM_ROLE;
SELECT CURRENT_ROLE();
SHOW GRANTS TO ROLE SNOWFLAKE_ROLE;
SHOW ROLES LIKE 'SNOWFLAKE_ROLE';

SELECT CURRENT_ROLE();
