name: Snowflake CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs when code is pushed to main
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.4"  # Uses the latest stable Python 3 version

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install snowflake-connector-python
          pip install snowflake-snowpark-python
          pip install python-dotenv

            

      - name: Execute Snowflake Notebooks
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          set -e  # Ensure script fails if any error occurs
           
          python Snowflake_notebook/Snowflake_function.py
